# Generated by Django 4.1.2 on 2022-10-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacture',
            new_name='Manufacturer',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='manufacture',
            new_name='manufacturer',
        ),
    ]
